<%-- _lcid="1033" _version="15.0.4420" _dal="1" --%>
<%-- _LocalBinding --%>
<%@ Page language="C#" MasterPageFile="~masterurl/default.master"      Inherits="Microsoft.Office.Server.WorkManagement.UI.MyTasksDashboardWebPartPage,Microsoft.Office.Server.WorkManagement.UI,Version=15.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %>
<%@ Register Tagprefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="Utilities" Namespace="Microsoft.SharePoint.Utilities" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="WebPartPages" Namespace="Microsoft.SharePoint.WebPartPages" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="OSRVWC" Namespace="Microsoft.Office.Server.WebControls" Assembly="Microsoft.Office.Server, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="OSRVUPWC" Namespace="Microsoft.Office.Server.WebControls" Assembly="Microsoft.Office.Server.UserProfiles, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="SPSWC" Namespace="Microsoft.SharePoint.Portal.WebControls" Assembly="Microsoft.SharePoint.Portal, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="SEARCHWC" Namespace="Microsoft.Office.Server.Search.WebControls" Assembly="Microsoft.Office.Server.Search, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="PublishingWebControls" Namespace="Microsoft.SharePoint.Publishing.WebControls" Assembly="Microsoft.SharePoint.Publishing, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<%@ Register TagPrefix="wssuc" TagName="NavItem" src="~/_controltemplates/15/NavItem.ascx" %>
<asp:Content contentplaceholderid="PlaceHolderPageTitleInTitleArea" runat="server">
  <SPSWC:PersonalSpaceRedirect runat="server" />
  <SPSWC:LabelLoc Text="<%$Resources:workmanagement, MyTasksDashboard_Title%>" runat="server" />
</asp:Content>
<asp:Content contentplaceholderid="PlaceHolderPageTitle" runat="server">
	<SharePoint:EncodedLiteral runat="server" text="<%$Resources:workmanagement, MyTasksDashboard_Title%>" EncodeMethod='HtmlEncode'/>
</asp:Content>
<asp:Content contentplaceholderid="PlaceHolderMain" runat="server">
  <div class="ms-alignright">
	<SPSWC:SetPersonalSiteButton runat="server" id="TBBPersonalSiteButton" class="ms-toolbar" ShowImageAndText="false"/>
  </div>
  <table border="0" cellpadding="0" cellspacing="0" ID="ZoneTable" width="100%"> <tr ID="TopRow" > <td valign="top" ID="TopCell" colspan="3"> <WebPartPages:WebPartZone runat="server" FrameType="TitleBarOnly" AllowPersonalization="true" ID="TopZone" Title="<%$Resources:sps,LayoutPageZone_TopZone%>" Orientation="Vertical" /> </td> </tr> <tr ID="MiddleRow"> <td valign="top" ID="MiddleLeftCell" width="60%" > <WebPartPages:WebPartZone runat="server" FrameType="TitleBarOnly" AllowPersonalization="true" ID="MiddleLeftZone" Title="<%$Resources:sps,LayoutPageZone_MiddleLeftZone%>" Orientation="Vertical" /> &#160; </td> <td style="padding:10px">&#160;</td> <td valign="top" ID="MiddleRightCell" width="40%"> <WebPartPages:WebPartZone runat="server" FrameType="TitleBarOnly" AllowPersonalization="true" ID="MiddleRightZone" Title="<%$Resources:sps,LayoutPageZone_MiddleRightZone%>" Orientation="Vertical" /> &#160; </td> </tr> <tr ID="BottomRow" class="ms-tzbottom"> <td valign="top" ID="BottomCell" colspan="3"> <WebPartPages:WebPartZone runat="server" FrameType="TitleBarOnly" AllowPersonalization="true" ID="BottomZone" Title="<%$Resources:sps,LayoutPageZone_BottomZone%>" Orientation="Vertical" /> </td> </tr> </table>
</asp:Content>
